--
-- TombolaApplication 3.14.15 Flyway script 
--
-- This SQL script creates the required tables

----- SEQUENCE hibernate_sequence -----

CREATE SEQUENCE hibernate_sequence INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;

/* -- CREATE SEQUENCE hibernate_sequence MINVALUE 1 START 1; */

CREATE SEQUENCE tombola_prize_id_seq INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;

CREATE SEQUENCE tombola_ticket_id_seq INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;

----- TABLE revinfo -----

CREATE TABLE revinfo (
    rev INT NOT NULL,
    revtstmp BIGINT NULL,
    CONSTRAINT revinfo_rev_pkey PRIMARY KEY (rev)
);


----- TABLE tombola_prize -----

CREATE TABLE tombola_prize (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    prize_name VARCHAR(255) NOT NULL,
    cnt INTEGER NOT NULL,
    issued INTEGER NOT NULL,
    created_date BIGINT NOT NULL,
    modified_date BIGINT NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    modified_by VARCHAR(255) NOT NULL,
    CONSTRAINT tombola_prize_id_pkey PRIMARY KEY (id),
    CONSTRAINT tombola_prize_name_uk UNIQUE (prize_name)
);


----- TABLE tombola_prize_a -----

CREATE TABLE tombola_prize_a (
    id BIGINT NOT NULL,
    rev INT REFERENCES revinfo (rev) NOT NULL,
    revtype SMALLINT NULL,
    prize_name VARCHAR(255) NOT NULL,
    prize_name_m BOOLEAN NULL,
    cnt INTEGER,
    cnt_m BOOLEAN NULL,
    issued INTEGER,
    issued_m BOOLEAN NULL,
    created_date BIGINT NULL,
    created_date_m BOOLEAN NULL,
    modified_date BIGINT NULL,
    modified_date_m BOOLEAN NULL,
    created_by VARCHAR(255) NULL,
    created_by_m BOOLEAN NULL,
    modified_by VARCHAR(255) NULL,
    modified_by_m BOOLEAN NULL,
    CONSTRAINT tombola_prize_a_pkey PRIMARY KEY (id, rev)
);
CREATE INDEX tombola_prize_a_rev_key ON tombola_prize_a USING btree (rev);


----- TABLE tombola_ticket  -----

CREATE TABLE tombola_ticket (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    win BIGINT NULL,
    created_date BIGINT NOT NULL,
    modified_date BIGINT NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    modified_by VARCHAR(255) NOT NULL,
    CONSTRAINT tombola_ticket_id_pkey PRIMARY KEY (id)
);


----- TABLE tombola_ticket_a  -----

CREATE TABLE tombola_ticket_a (
    id BIGINT NOT NULL,
    rev INT REFERENCES revinfo (rev) NOT NULL,
    revtype SMALLINT NULL,
    win BIGINT NULL,
    win_m BOOLEAN NULL,
    created_date BIGINT NULL,
    created_date_m BOOLEAN NULL,
    modified_date BIGINT NULL,
    modified_date_m BOOLEAN NULL,
    created_by VARCHAR(255) NULL,
    created_by_m BOOLEAN NULL,
    modified_by VARCHAR(255) NULL,
    modified_by_m BOOLEAN NULL,
    CONSTRAINT tombola_ticket_a_pkey PRIMARY KEY (id, rev)
);
CREATE INDEX tombola_ticket_a_rev_key ON tombola_ticket_a USING btree (rev);


----- TABLE tombola_prize_ticket  -----

CREATE TABLE tombola_prize_ticket (
    prize_id BIGINT REFERENCES tombola_prize (id) NOT NULL,
    ticket_id BIGINT REFERENCES tombola_ticket (id) NOT NULL,
    CONSTRAINT tombola_prize_ticket_pkey PRIMARY KEY (prize_id, ticket_id),
    CONSTRAINT tombola_prize_ticket_id_uk UNIQUE (ticket_id)
);
CREATE INDEX key_tombola_prize_ticket_prize_id ON tombola_prize_ticket (prize_id);


----- TABLE tombola_role -----

CREATE TABLE tombola_role (
  id BIGINT NOT NULL,
  role_name VARCHAR(255) NOT NULL,
  enabled BOOLEAN,
  CONSTRAINT tombola_role_id_pkey PRIMARY KEY (id),
  CONSTRAINT tombola_role_name_uk UNIQUE (role_name)
);


----- TABLE tombola_user -----

CREATE TABLE tombola_user (
  id BIGINT NOT NULL,
  user_name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  account_non_expired BOOLEAN,
  account_non_locked BOOLEAN,
  credentials_non_expired BOOLEAN,
  enabled BOOLEAN,
  CONSTRAINT tombola_user_id_pkey PRIMARY KEY (id),
  CONSTRAINT tombola_user_name_uk UNIQUE (user_name)
);


----- TABLE tombola_user_role -----

CREATE TABLE tombola_user_role (
  user_id BIGINT REFERENCES tombola_user (id) NOT NULL,
  role_id BIGINT REFERENCES tombola_role (id) NOT NULL,
  CONSTRAINT tombola_user_role_pkey PRIMARY KEY (user_id, role_id)
);


----- VIEW tombola_view -----

CREATE VIEW tombola_view AS SELECT ROW_NUMBER() OVER (ORDER BY a.id, c.id) as id, a.id user_id, a.user_name,
  a.enabled user_enabled, c.id role_id, c.role_name, c.enabled role_enabled FROM tombola_user a
  JOIN tombola_user_role b ON a.id = b.user_id JOIN tombola_role c ON b.role_id = c.id ORDER BY a.id, c.id;

 
----- VIEW tombola_prize_view -----

CREATE VIEW tombola_prize_view AS SELECT
  id, prize_name, cnt, issued,
  CASE WHEN created_date = 0 THEN '' ELSE
        TO_CHAR(TO_TIMESTAMP(created_date / 1000),
        'YYYY-MM-DD HH24:MI:SS') END created_date,
  created_by,  
  CASE WHEN modified_date = 0 THEN '' ELSE
        TO_CHAR(TO_TIMESTAMP(modified_date / 1000),
        'YYYY-MM-DD HH24:MI:SS') END modified_date,
  modified_by
  FROM tombola_prize ORDER BY id;

  
----- VIEW tombola_prize_a_view -----

CREATE VIEW tombola_prize_a_view AS SELECT
  TO_CHAR(TO_TIMESTAMP(revtstmp / 1000),
    'YYYY-MM-DD HH24:MI:SS') revdate,
  a.id, a.rev, a.revtype,
  prize_name, cnt, issued,
  CASE WHEN created_date = 0 THEN '' ELSE
    TO_CHAR(TO_TIMESTAMP(created_date / 1000),
      'YYYY-MM-DD HH24:MI:SS') END created_date,
  created_by,  
  CASE WHEN modified_date = 0 THEN '' ELSE
    TO_CHAR(TO_TIMESTAMP(modified_date / 1000),
      'YYYY-MM-DD HH24:MI:SS') END modified_date,
  modified_by
  FROM tombola_prize_a a, revinfo r WHERE a.rev = r.rev ORDER BY revtstmp, id, rev;

  
----- VIEW tombola_ticket_view -----

CREATE VIEW tombola_ticket_view AS SELECT
  id, win,
  CASE WHEN created_date = 0 THEN '' ELSE
        TO_CHAR(TO_TIMESTAMP(created_date / 1000),
        'YYYY-MM-DD HH24:MI:SS') END created_date,
  created_by,  
  CASE WHEN modified_date = 0 THEN '' ELSE
        TO_CHAR(TO_TIMESTAMP(modified_date / 1000),
        'YYYY-MM-DD HH24:MI:SS') END modified_date,
  modified_by
  FROM tombola_ticket ORDER BY id;

  
----- VIEW tombola_ticket_a_view -----

CREATE VIEW tombola_ticket_a_view AS SELECT
  TO_CHAR(TO_TIMESTAMP(revtstmp / 1000),
    'YYYY-MM-DD HH24:MI:SS') revdate,
  a.id, a.rev, a.revtype,
  win,
  CASE WHEN created_date = 0 THEN '' ELSE
    TO_CHAR(TO_TIMESTAMP(created_date / 1000),
      'YYYY-MM-DD HH24:MI:SS') END created_date,
  created_by,  
  CASE WHEN modified_date = 0 THEN '' ELSE
    TO_CHAR(TO_TIMESTAMP(modified_date / 1000),
      'YYYY-MM-DD HH24:MI:SS') END modified_date,
  modified_by
  FROM tombola_ticket_a a, revinfo r WHERE a.rev = r.rev ORDER BY revtstmp, id, rev;
